order

diff --git a/.github/workflows/main-branch-protection.yml b/.github/workflows/main-branch-protection.yml
--- a/.github/workflows/main-branch-protection.yml
+++ b/.github/workflows/main-branch-protection.yml
@@ -11,7 +11,16 @@ jobs:
   check-branch:
     runs-on: ubuntu-latest
     steps:
+      - name: Check branch
+        run: |
+          if [[ ${GITHUB_HEAD_REF} != staging ]] && ! [[ ${GITHUB_HEAD_REF} =~ ^hotfix/ ]]; 
+          then
+            echo "Error: Pull request must come from 'staging' or 'hotfix/' branch"
+            exit 1
+          fi
+
       - name: Create comment
+        if: failure() # Run this step only if the previous step fails
         uses: actions/github-script@v6
         with:
           script: |
@@ -21,11 +30,3 @@ jobs:
               repo: context.repo.repo,
               body: '🚫 Error: Pull request must come from staging or hotfix/ branch'
             })
-
-      - name: Check branch
-        run: |
-          if [[ ${GITHUB_HEAD_REF} != staging ]] && ! [[ ${GITHUB_HEAD_REF} =~ ^hotfix/ ]]; 
-          then
-            echo "Error: Pull request must come from 'staging' or 'hotfix/' branch"
-            exit 1
-          fi
